### ISSUE TITLE
Program Crashes 

### ISSUE THREAD

**Issue by rachitchokshi** [AhmadYahya97/Fully-Automated-red-light-Violation-Detection#3]
Hello,

While trying to run the project through below command

```
python ~/Fully-Automated-red-light-Violation-Detection/yolo_video_new.py -i ~/Fully-Automated-red-light-Violation-Detection/videos/aziz1.MP4 -o ~/Fully-Automated-red-light-Violation-Detection/videos -y ~/Fully-Automated-red-light-Violation-Detection/yolo-coco/
```

The program crashes with below error

    INFO] loading YOLO from disk...
    [INFO] 120 total frames in video
    Traceback (most recent call last):
      File "/home/xxxx/PR/Fully-Automated-red-light-Violation-Detection/yolo_video_new.py", line 314, in <module>
        thresholdRedLight = getLightThresh(showStages=True)
      File "/home/xxxx/PR/Fully-Automated-red-light-Violation-Detection/yolo_video_new.py", line 249, in getLightThresh
        im2, contours, hierarchy = cv2.findContours(th, cv2.RETR_TREE, cv2.CHAIN_APPROX_TC89_KCOS)
    ValueError: not enough values to unpack (expected 3, got 2)

After fixing this one it crashes with

    Traceback (most recent call last):
      File "/home/xxxx/PR/Fully-Automated-red-light-Violation-Detection/yolo_video_new.py", line 516, in <module>
        boxesTemp = updateTrackers(frame)
      File "/home/xxxx/PR/Fully-Automated-red-light-Violation-Detection/yolo_video_new.py", line 411, in updateTrackers
        tracker, box = trackersList[n]
    IndexError: list index out of range 

### Steps to Reproduce on a linux x86_64 machine

    cd $HOME
    git clone [https://github.com/AhmadYahya97/Fully-Automated-red-light-Violation-Detection](https://github.com/AhmadYahya97/Fully-Automated-red-light-Violation-Detection)
    cd Fully-Automated-red-light-Violation-Detection/
    python3 -m virtualenv venv
    source venv/bin/activate
    pip install numpy imutils matplotlib opencv-python opencv-contrib-python
    python ~/Fully-Automated-red-light-Violation-Detection/yolo_video_new.py -i ~/Fully-Automated-red-light-Violation-Detection/videos/aziz1.MP4 -o ~/Fully-Automated-red-light-Violation-Detection/videos -y ~/Fully-Automated-red-light-Violation-Detection/yolo-coco/

**Comment by Azhar1504** [comment]
Hey, in your command to run it, you have correctly given an input video but not the output video. You have given it a directory instead of a .mp4 file, maybe this could be the problem?

**Comment by Azhar1504** [comment]
Try changing the --output to something like test.avi?

**Comment by Yaoxiao1** [comment]
Hi, about the IndexError: list index out of range , I think that might be a variable naming problem.
checke the line 395
![image](https://user-images.githubusercontent.com/34466246/78319937-e07e2c00-759a-11ea-8242-b71092a3f58f.png)
see the enumerate variable "n",  it crashes with the upper variable "n" so you got a index problem, just change it to another name (for me I change it to "nn") and that would be fine.

Hoping it would help

**Comment by Green00101** [comment]
cv2.error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\dnn\src\darknet\darknet_io.cpp:712: error: (-213:The function/feature is not implemented) Transpose the weights (except for convolutional) is not implemented in function 'cv::dnn::darknet::ReadDarknetFromWeightsStream'

what should i do？

**Comment by Yaoxiao1** [comment]
> cv2.error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\dnn\src\darknet\darknet_io.cpp:712: error: (-213:The function/feature is not implemented) Transpose the weights (except for convolutional) is not implemented in function 'cv::dnn::darknet::ReadDarknetFromWeightsStream'
> 
> what should i do？

go download any yolo-weight(approximately 280M) and replace the one in this directory

**Comment by Green00101** [comment]
> > cv2.error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\dnn\src\darknet\darknet_io.cpp:712: error: (-213:The function/feature is not implemented) Transpose the weights (except for convolutional) is not implemented in function 'cv::dnn::darknet::ReadDarknetFromWeightsStream'
> > what should i do？
> 
> go download any yolo-weight(approximately 280M) and replace the one in this directory

I solve that problem， thanks a lot

**Comment by Green00101** [comment]
![image](https://user-images.githubusercontent.com/54564107/81731016-f1d32600-94c0-11ea-8c1b-f8f8a3c7c06c.png)

How do I slove this problem， and if its wrong it will told me

Traceback (most recent call last):
  File "yolo_video_new.py", line 387, in <module>
    boxesTemp = updateTrackers(frame)
  File "yolo_video_new.py", line 320, in updateTrackers
    tracker, box = trackersList[n]
IndexError: list index out of range

**Comment by rutuja1409** [comment]
cv2.error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\highgui\src\window.cpp:651: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvShowImage'

I am 

> ![image](https://user-images.githubusercontent.com/54564107/81731016-f1d32600-94c0-11ea-8c1b-f8f8a3c7c06c.png)
> 
> How do I slove this problem， and if its wrong it will told me
> 
> Traceback (most recent call last):
> File "yolo_video_new.py", line 387, in
> boxesTemp = updateTrackers(frame)
> File "yolo_video_new.py", line 320, in updateTrackers
> tracker, box = trackersList[n]
> IndexError: list index out of range

cv2.error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\highgui\src\window.cpp:651: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvShowImage'

I am getting this error.. Can you help me solve this please @Green00101 
Thank you.

**Comment by rutuja1409** [comment]
> ![image](https://user-images.githubusercontent.com/54564107/81731016-f1d32600-94c0-11ea-8c1b-f8f8a3c7c06c.png)
> 
> How do I slove this problem， and if its wrong it will told me
> 
> Traceback (most recent call last):
> File "yolo_video_new.py", line 387, in
> boxesTemp = updateTrackers(frame)
> File "yolo_video_new.py", line 320, in updateTrackers
> tracker, box = trackersList[n]
> IndexError: list index out of range

I am getting the same error. Can you tell me how did u solve it ??
Thank you..

**Comment by rachitchokshi** [comment]
Look above comments, @Yaoxiao1 has a solution which should work 
> > ![image](https://user-images.githubusercontent.com/54564107/81731016-f1d32600-94c0-11ea-8c1b-f8f8a3c7c06c.png)
> > How do I slove this problem， and if its wrong it will told me
> > Traceback (most recent call last):
> > File "yolo_video_new.py", line 387, in
> > boxesTemp = updateTrackers(frame)
> > File "yolo_video_new.py", line 320, in updateTrackers
> > tracker, box = trackersList[n]
> > IndexError: list index out of range
> 
> I am getting the same error. Can you tell me how did u solve it ??
> Thank you..

**Comment by rutuja1409** [comment]
> Look above comments, @Yaoxiao1 has a solution which should work
> 
> > > ![image](https://user-images.githubusercontent.com/54564107/81731016-f1d32600-94c0-11ea-8c1b-f8f8a3c7c06c.png)
> > > How do I slove this problem， and if its wrong it will told me
> > > Traceback (most recent call last):
> > > File "yolo_video_new.py", line 387, in
> > > boxesTemp = updateTrackers(frame)
> > > File "yolo_video_new.py", line 320, in updateTrackers
> > > tracker, box = trackersList[n]
> > > IndexError: list index out of range
> > 
> > 
> > I am getting the same error. Can you tell me how did u solve it ??
> > Thank you..

Thank you for the solution. Can I increase the frame size or some other method which will increase the speed to get output faster? Please guide .

**Comment by ezratoga** [comment]
When i tried run the code:
python ~/Fully-Automated-red-light-Violation-Detection/yolo_video_new.py -i ~/Fully-Automated-red-light-Violation-Detection/videos/aziz1.MP4 -o ~/Fully-Automated-red-light-Violation-Detection/videos -y ~/Fully-Automated-red-light-Violation-Detection/yolo-coco/

there was an error like this : 
Traceback (most recent call last):
  File "yolo_video_new.py", line 115, in <module>
    "csrt": cv2.TrackerCSRT_create,
AttributeError: module 'cv2.cv2' has no attribute 'TrackerCSRT_create'

Anyone can help me?

**Comment by durgeshkulkarni1999** [comment]
You have install full opencv library for that you have to 
1. Uninstall current opencv version by using pip uninstall opencv-python.
2. Then install by using pip install opencv-contrib-python.

**Comment by durgeshkulkarni1999** [comment]
> When i tried run the code:
> python ~/Fully-Automated-red-light-Violation-Detection/yolo_video_new.py -i ~/Fully-Automated-red-light-Violation-Detection/videos/aziz1.MP4 -o ~/Fully-Automated-red-light-Violation-Detection/videos -y ~/Fully-Automated-red-light-Violation-Detection/yolo-coco/
> 
> there was an error like this :
> Traceback (most recent call last):
> File "yolo_video_new.py", line 115, in
> "csrt": cv2.TrackerCSRT_create,
> AttributeError: module 'cv2.cv2' has no attribute 'TrackerCSRT_create'
> 
> Anyone can help me?




You have install full opencv library for that you have to

Uninstall current opencv version by using pip uninstall opencv-python.
Then install by using pip install opencv-contrib-python.

**Comment by sifodev** [comment]
> > When i tried run the code:
> > python ~/Fully-Automated-red-light-Violation-Detection/yolo_video_new.py -i ~/Fully-Automated-red-light-Violation-Detection/videos/aziz1.MP4 -o ~/Fully-Automated-red-light-Violation-Detection/videos -y ~/Fully-Automated-red-light-Violation-Detection/yolo-coco/
> > there was an error like this :
> > Traceback (most recent call last):
> > File "yolo_video_new.py", line 115, in
> > "csrt": cv2.TrackerCSRT_create,
> > AttributeError: module 'cv2.cv2' has no attribute 'TrackerCSRT_create'
> > Anyone can help me?
> 
> You have install full opencv library for that you have to
> 
> Uninstall current opencv version by using pip uninstall opencv-python.
> Then install by using pip install opencv-contrib-python.

u can use opencv-contrib-python==4.2.0.34
it will solve the issue for me

**Comment by sifodev** [comment]
> Hello,
> 
> While trying to run the project through below command
> 
> ```
> python ~/Fully-Automated-red-light-Violation-Detection/yolo_video_new.py -i ~/Fully-Automated-red-light-Violation-Detection/videos/aziz1.MP4 -o ~/Fully-Automated-red-light-Violation-Detection/videos -y ~/Fully-Automated-red-light-Violation-Detection/yolo-coco/
> ```
> 
> The program crashes with below error
> 
> ```
> INFO] loading YOLO from disk...
> [INFO] 120 total frames in video
> Traceback (most recent call last):
>   File "/home/xxxx/PR/Fully-Automated-red-light-Violation-Detection/yolo_video_new.py", line 314, in <module>
>     thresholdRedLight = getLightThresh(showStages=True)
>   File "/home/xxxx/PR/Fully-Automated-red-light-Violation-Detection/yolo_video_new.py", line 249, in getLightThresh
>     im2, contours, hierarchy = cv2.findContours(th, cv2.RETR_TREE, cv2.CHAIN_APPROX_TC89_KCOS)
> ValueError: not enough values to unpack (expected 3, got 2)
> ```
> 
> After fixing this one it crashes with
> 
> ```
> Traceback (most recent call last):
>   File "/home/xxxx/PR/Fully-Automated-red-light-Violation-Detection/yolo_video_new.py", line 516, in <module>
>     boxesTemp = updateTrackers(frame)
>   File "/home/xxxx/PR/Fully-Automated-red-light-Violation-Detection/yolo_video_new.py", line 411, in updateTrackers
>     tracker, box = trackersList[n]
> IndexError: list index out of range 
> ```
> 
> ### Steps to Reproduce on a linux x86_64 machine
> ```
> cd $HOME
> git clone [https://github.com/AhmadYahya97/Fully-Automated-red-light-Violation-Detection](https://github.com/AhmadYahya97/Fully-Automated-red-light-Violation-Detection)
> cd Fully-Automated-red-light-Violation-Detection/
> python3 -m virtualenv venv
> source venv/bin/activate
> pip install numpy imutils matplotlib opencv-python opencv-contrib-python
> python ~/Fully-Automated-red-light-Violation-Detection/yolo_video_new.py -i ~/Fully-Automated-red-light-Violation-Detection/videos/aziz1.MP4 -o ~/Fully-Automated-red-light-Violation-Detection/videos -y ~/Fully-Automated-red-light-Violation-Detection/yolo-coco/
> ```

how you solve the first error that u mentioned?

**Comment by Mosh094** [comment]
Anyone has ran this on windows? I am having trouble running it

**Comment by Guttappa1238** [comment]
Hi,
i'm getting the same error how to solve this:

```
Traceback (most recent call last):
  File "yolo_video_new.py", line 516, in <module>
    boxesTemp = updateTrackers(frame)
  File "yolo_video_new.py", line 411, in updateTrackers
    tracker, box = trackersList[nn]
IndexError: list index out of range
```
